### ISSUE TITLE
Is ramsql threadsafe?

### ISSUE THREAD

**Issue by bketelsen** [proullon/ramsql#2]
Go tests run in parallel, will each test have its own instance of ramsql?

**Comment by proullon** [comment]
It depends of the given datasource name.

There is a unique instance of ramsql per datasource name. Typically, I use the test name as DSN to be sure I have what I want. 
If there is already an instance linked to the DSN, it will be used (it allow the sql.DB to do its job, opening as many connections as needed)

Was that clear ?

**Comment by bketelsen** [comment]
Yes thanks!
