### ISSUE TITLE
parsing error near unique not null

### ISSUE THREAD

**Issue by dfong** [proullon/ramsql#21]
with ramsql i get the above error on this statement,

create table tables(name text unique not null)

which works fine if i use the sqlite3 driver instead.

**Comment by proullon** [comment]
yes unique is not implemented (it's #15 )
I'll see what I can do this week

**Comment by proullon** [comment]
done

**Comment by dfong** [comment]
thanks for rapidly fixing these bugs.

**Comment by fabulias** [comment]
But `UNIQUE` only works as `column constraint`, I try with `table constraint` and the output is an error.

I want:
`CREATE TABLE IF NOT EXISTS sample_table (id SERIAL PRIMARY KEY, name TEXT, UNIQUE(name));`
I got:
`ERROR : cannot execute : Syntax error near , unique (`

If I try with this:
`CREATE TABLE IF NOT EXISTS sample_table (id SERIAL PRIMARY KEY, name TEXT UNIQUE);`
I got:
`Query OK. 1 rows affected`
