### ISSUE TITLE
Implement SCHEMA

### ISSUE THREAD

**Issue by dabfleming** [proullon/ramsql#39]
Was just giving this a try for testing a project and our schema creation sql looks something like:

```sql
CREATE SCHEMA foo;

CREATE TABLE "foo"."bar"
{
  ...
}
...
```

ramsql seems to fail on both `SCHEMA` and the compound table name, ie it wants to create table `foo` and treats `."bar"` as incorrect.

**Comment by aramcodz** [comment]
+1. I would also find this helpful.

**Comment by oliverisaac** [comment]
This would be useful for being able to test user management features as well.

**Comment by proullon** [comment]
Hi there,

Looking into it
