### ISSUE TITLE
CREATE UNIQUE INDEX

### ISSUE THREAD

**Issue by xleyba** [proullon/ramsql#58]
Hi

I have tried to use this library for testing but it fails when try to do this:

```go
const creatArtist string = `
  CREATE TABLE IF NOT EXISTS artist (
  	id VARCHAR(255) NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
  );`
const createIndex string = `CREATE UNIQUE INDEX IF NOT EXISTS nameindex ON artist(name COLLATE NOCASE);`

// Open the in memory DB
	db, err := sql.Open("ramsql", "TestRead")
	if err != nil {
		t.Fatalf("sql.Open : Error : %s\n", err)
	}
	defer db.Close()

if _, err := db.Exec(creatArtist); err != nil {
		log.Fatal("Error creating DB %v", err)
		return nil, err
	}

	if _, err := db.Exec(createIndex); err != nil {
		log.Fatal("Error creating Index %v", err)
		return nil, err
	}
```

and then got error saying "error near to UNIQUE" when creating index.

That index creating is standard and works fine with several SQL DB flavors.

**Comment by proullon** [comment]
Hi,

CREATE INDEX is not implemented in RamSQL, I added a test case in branch [feat/58](https://github.com/proullon/ramsql/compare/master...feat/58), I'll check to see if there is a lot of work to parse this.
