### ISSUE TITLE
If you use GORM, please use Postgres driver

### ISSUE THREAD

**Issue by sneko** [proullon/ramsql#59]
Hi,

Just here to note that if you intend to use `ramsql` with the `GORM` ORM, you should use the GORM Postgres driver, not the MySQL one otherwise you will get an error.

A working example would be:
```
	sqlDB, err := sql.Open("ramsql", "Test")
	...

	db, err := gorm.Open(postgres.New(postgres.Config{
		Conn: sqlDB,
	}), &gorm.Config{})
```

Hope it helps 👍

**Comment by proullon** [comment]
Thanks !
