### ISSUE TITLE
Sometimes ORM wrap columns with quotes

### ISSUE THREAD

**Issue by sneko** [proullon/ramsql#62]
Hi @proullon ,

Some ORM wrap columns with quotes as in the example of GORM:
```sql
UPDATE "challenges" SET "deleted_at"='2022-07-11 14:52:45.804' WHERE "challenges"."deleted_at" IS NULL
```

But I get this error:
```
Syntax error near . \" deleted_at
```

Note that when testing the followings it works perfectly:

```sql
UPDATE "challenges" SET "deleted_at"='2022-07-11 14:52:45.804' WHERE "challenges".deleted_at IS NULL
```

```sql
UPDATE "challenges" SET "deleted_at"='2022-07-11 14:52:45.804' WHERE challenges.deleted_at IS NULL
```

Is it possible you accept quotes for columns as you do for tables?

Thank you,

**Comment by proullon** [comment]
Hi,

indeed it should be handled, and would not be hard to do. Unfortunately I have very few coding time right now sorry. I'll try to get to it soon.

Maybe you can give it a go ?

**Comment by pkordes** [comment]
Would this be a driver issue?  I am having the same issue when using gorm

**Comment by proullon** [comment]
Hi,

It should be good for this issue, I'll try  to setup  a  test suite with gorm

**Comment by sneko** [comment]
Thank you @proullon !

Note: another thing among GORM issues is https://github.com/proullon/ramsql/pull/61#issuecomment-1180283626 when trying to migrate schemas to the DB.
