### ISSUE TITLE
Handling brackets in WHERE clauses

### ISSUE THREAD

**Issue by sneko** [proullon/ramsql#67]
Hi,

Same as the old issue #27 that is closed.

The error I get is:
```
Syntax error near where ( created_at
```

With the query:
```sql
SELECT * FROM "users" WHERE (created_at < '2019-12-31 00:00:00')
```

(I had a more complex query but I reduced it to show it comes from brackets even with no nested conditions)

@proullon as you mentioned in https://github.com/proullon/ramsql/issues/62#issuecomment-1188813979 I really do understand the pain of handling all parsing cases. Any news on handling the SQL BNF? Maybe you could add the comment you wrote on the `README.md` so that people see it?

_(in the meantime I will go with a sidecar container of my DB to handle all complex cases with GORM)_

Thank you for your work, it's still useful to test common cases without dealing with external binary!

**Comment by proullon** [comment]
Sorry, took a bit of time -_-'
