### ISSUE TITLE
Bug(regression): Relation attrIndex keys are in lower case but lookup is not

### ISSUE THREAD

**Issue by trakhimenok** [proullon/ramsql#86]
Started to get this error after upgrading from `v0.0.1` to `v0.1.0`: 
```Go
"attribute not defined"
```

I have this table definition:

```SQL
CREATE TABLE DalgoE2E_E2ETest1 (ID1 VARCHAR(10) PRIMARY KEY, StringProp TEXT, IntegerProp INT);
```

And am trying to query data as:
```SQL
SELECT StringProp, IntegerProp FROM DalgoE2E_E2ETest1
```

Column names comes to the `func (r *Relation) Attribute(name string) (int, Attribute, error)` in original CamelCase but are in lower case in `Relation.attrIndex`.

I believe [this line](https://github.com/proullon/ramsql/blob/e12c9872c05dfd96f12daef316ce7398581defac/engine/agnostic/relation.go#L60) should bring the `name` to lowercase like:

```Go
index, ok := r.attrIndex[strings.ToLower(name)]
```

**Comment by proullon** [comment]
Issue is still present, cf failing test in #fix/86
