### ISSUE TITLE
"attribute not defined" error should state _which_ attribute it can't find

### ISSUE THREAD

**Issue by parkr** [proullon/ramsql#89]
Started to get this error after upgrading from v0.0.1 to v0.1.0:

    "attribute not defined"

It would be helpful to indicate which attribute it missing, e.g.

    attribute not defined: attributeName

Bonus points if it were to also mention the table name, e.g. 

    attribute not defined: table_name.attributeName

**Comment by proullon** [comment]
indeed, error message should be better.

Leaving this issue open to fix it, thanks !

**Comment by parkr** [comment]
Thank you so much!
