### ISSUE TITLE
I can't add in false values in an insert statement

### ISSUE THREAD

**Issue by Joematpal** [proullon/ramsql#93]
I use this with sqlx primarily the "NamedExec" func. I can't insert false values into the db. It throws a syntax error. 

I can enter in a true value. The "empty" value for a boolean is false. When a struct has an empty bool I can't add that value to the db.

#92

**Comment by Joematpal** [comment]
@proullon 

The tests don't actually test putting in a false to the db. 

The tests also don't regularly test the argument substitution. 

The test and package don't treat the order of the argument substitution like other sql packages do. This package wants the order to be that of the order of the statements in the create statement. Not of the sql statement you want to execute.

**Comment by proullon** [comment]
Hi,

Thanks for reporting, this is really strange. I'll take a look

**Comment by proullon** [comment]
Ok so `db.Exec("INSERT INTO cat (breed, name, funny) VALUES ('indeterminate', 'Uhura', false)")` is enough to trigger the syntax error. I'll update the parser

**Comment by proullon** [comment]
Can you check `@v0.1.3`  ?

**Comment by Joematpal** [comment]
Yes there is also an issue with the order of the arguments that get passed in. The substitutions really need to be used more in the tests.

**Comment by proullon** [comment]
I'm sorry, I don't understand. Can you give me an example ?
